package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table carpart_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CarpartInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_info.carpart_id
     *
     * @mbggenerated
     */
    private Integer carpartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_info.carpart_name
     *
     * @mbggenerated
     */
    private String carpartName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_info.manufacturer
     *
     * @mbggenerated
     */
    private String manufacturer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_info.carpart_price
     *
     * @mbggenerated
     */
    private Integer carpartPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_info.reserve_amount
     *
     * @mbggenerated
     */
    private Integer reserveAmount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_info.carpart_id
     *
     * @return the value of carpart_info.carpart_id
     *
     * @mbggenerated
     */
    public Integer getCarpartId() {
        return carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_info.carpart_id
     *
     * @param carpartId the value for carpart_info.carpart_id
     *
     * @mbggenerated
     */
    public void setCarpartId(Integer carpartId) {
        this.carpartId = carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_info.carpart_name
     *
     * @return the value of carpart_info.carpart_name
     *
     * @mbggenerated
     */
    public String getCarpartName() {
        return carpartName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_info.carpart_name
     *
     * @param carpartName the value for carpart_info.carpart_name
     *
     * @mbggenerated
     */
    public void setCarpartName(String carpartName) {
        this.carpartName = carpartName == null ? null : carpartName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_info.manufacturer
     *
     * @return the value of carpart_info.manufacturer
     *
     * @mbggenerated
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_info.manufacturer
     *
     * @param manufacturer the value for carpart_info.manufacturer
     *
     * @mbggenerated
     */
    public void setManufacturer(String manufacturer) {
        this.manufacturer = manufacturer == null ? null : manufacturer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_info.carpart_price
     *
     * @return the value of carpart_info.carpart_price
     *
     * @mbggenerated
     */
    public Integer getCarpartPrice() {
        return carpartPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_info.carpart_price
     *
     * @param carpartPrice the value for carpart_info.carpart_price
     *
     * @mbggenerated
     */
    public void setCarpartPrice(Integer carpartPrice) {
        this.carpartPrice = carpartPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_info.reserve_amount
     *
     * @return the value of carpart_info.reserve_amount
     *
     * @mbggenerated
     */
    public Integer getReserveAmount() {
        return reserveAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_info.reserve_amount
     *
     * @param reserveAmount the value for carpart_info.reserve_amount
     *
     * @mbggenerated
     */
    public void setReserveAmount(Integer reserveAmount) {
        this.reserveAmount = reserveAmount;
    }
}