package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table carpart_usage
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CarpartUsage extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_usage.usage_id
     *
     * @mbggenerated
     */
    private Integer usageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_usage.repair_id
     *
     * @mbggenerated
     */
    private Integer repairId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_usage.carpart_id
     *
     * @mbggenerated
     */
    private Integer carpartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_usage.usage_amount
     *
     * @mbggenerated
     */
    private Integer usageAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column carpart_usage.usage_date
     *
     * @mbggenerated
     */
    private Date usageDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_usage.usage_id
     *
     * @return the value of carpart_usage.usage_id
     *
     * @mbggenerated
     */
    public Integer getUsageId() {
        return usageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_usage.usage_id
     *
     * @param usageId the value for carpart_usage.usage_id
     *
     * @mbggenerated
     */
    public void setUsageId(Integer usageId) {
        this.usageId = usageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_usage.repair_id
     *
     * @return the value of carpart_usage.repair_id
     *
     * @mbggenerated
     */
    public Integer getRepairId() {
        return repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_usage.repair_id
     *
     * @param repairId the value for carpart_usage.repair_id
     *
     * @mbggenerated
     */
    public void setRepairId(Integer repairId) {
        this.repairId = repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_usage.carpart_id
     *
     * @return the value of carpart_usage.carpart_id
     *
     * @mbggenerated
     */
    public Integer getCarpartId() {
        return carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_usage.carpart_id
     *
     * @param carpartId the value for carpart_usage.carpart_id
     *
     * @mbggenerated
     */
    public void setCarpartId(Integer carpartId) {
        this.carpartId = carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_usage.usage_amount
     *
     * @return the value of carpart_usage.usage_amount
     *
     * @mbggenerated
     */
    public Integer getUsageAmount() {
        return usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_usage.usage_amount
     *
     * @param usageAmount the value for carpart_usage.usage_amount
     *
     * @mbggenerated
     */
    public void setUsageAmount(Integer usageAmount) {
        this.usageAmount = usageAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column carpart_usage.usage_date
     *
     * @return the value of carpart_usage.usage_date
     *
     * @mbggenerated
     */
    public Date getUsageDate() {
        return usageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column carpart_usage.usage_date
     *
     * @param usageDate the value for carpart_usage.usage_date
     *
     * @mbggenerated
     */
    public void setUsageDate(Date usageDate) {
        this.usageDate = usageDate;
    }
}