package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table client_repair
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ClientRepair extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.repair_id
     *
     * @mbggenerated
     */
    private Integer repairId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.register_id
     *
     * @mbggenerated
     */
    private Integer registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.mechanic_id
     *
     * @mbggenerated
     */
    private Integer mechanicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.repair_task
     *
     * @mbggenerated
     */
    private String repairTask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.carpart_id
     *
     * @mbggenerated
     */
    private Integer carpartId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_repair.finish_date
     *
     * @mbggenerated
     */
    private Date finishDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.repair_id
     *
     * @return the value of client_repair.repair_id
     *
     * @mbggenerated
     */
    public Integer getRepairId() {
        return repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.repair_id
     *
     * @param repairId the value for client_repair.repair_id
     *
     * @mbggenerated
     */
    public void setRepairId(Integer repairId) {
        this.repairId = repairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.register_id
     *
     * @return the value of client_repair.register_id
     *
     * @mbggenerated
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.register_id
     *
     * @param registerId the value for client_repair.register_id
     *
     * @mbggenerated
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.mechanic_id
     *
     * @return the value of client_repair.mechanic_id
     *
     * @mbggenerated
     */
    public Integer getMechanicId() {
        return mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.mechanic_id
     *
     * @param mechanicId the value for client_repair.mechanic_id
     *
     * @mbggenerated
     */
    public void setMechanicId(Integer mechanicId) {
        this.mechanicId = mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.repair_task
     *
     * @return the value of client_repair.repair_task
     *
     * @mbggenerated
     */
    public String getRepairTask() {
        return repairTask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.repair_task
     *
     * @param repairTask the value for client_repair.repair_task
     *
     * @mbggenerated
     */
    public void setRepairTask(String repairTask) {
        this.repairTask = repairTask == null ? null : repairTask.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.carpart_id
     *
     * @return the value of client_repair.carpart_id
     *
     * @mbggenerated
     */
    public Integer getCarpartId() {
        return carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.carpart_id
     *
     * @param carpartId the value for client_repair.carpart_id
     *
     * @mbggenerated
     */
    public void setCarpartId(Integer carpartId) {
        this.carpartId = carpartId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_repair.finish_date
     *
     * @return the value of client_repair.finish_date
     *
     * @mbggenerated
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_repair.finish_date
     *
     * @param finishDate the value for client_repair.finish_date
     *
     * @mbggenerated
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
}