package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table client_car
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class ClientCar extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.register_id
     *
     * @mbggenerated
     */
    private Integer registerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.owner_name
     *
     * @mbggenerated
     */
    private String ownerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.car_id
     *
     * @mbggenerated
     */
    private String carId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.register_date
     *
     * @mbggenerated
     */
    private Date registerDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.car_type
     *
     * @mbggenerated
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.owner_phone
     *
     * @mbggenerated
     */
    private String ownerPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_car.owner_email
     *
     * @mbggenerated
     */
    private String ownerEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.register_id
     *
     * @return the value of client_car.register_id
     *
     * @mbggenerated
     */
    public Integer getRegisterId() {
        return registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.register_id
     *
     * @param registerId the value for client_car.register_id
     *
     * @mbggenerated
     */
    public void setRegisterId(Integer registerId) {
        this.registerId = registerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.owner_name
     *
     * @return the value of client_car.owner_name
     *
     * @mbggenerated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.owner_name
     *
     * @param ownerName the value for client_car.owner_name
     *
     * @mbggenerated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.car_id
     *
     * @return the value of client_car.car_id
     *
     * @mbggenerated
     */
    public String getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.car_id
     *
     * @param carId the value for client_car.car_id
     *
     * @mbggenerated
     */
    public void setCarId(String carId) {
        this.carId = carId == null ? null : carId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.register_date
     *
     * @return the value of client_car.register_date
     *
     * @mbggenerated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.register_date
     *
     * @param registerDate the value for client_car.register_date
     *
     * @mbggenerated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.car_type
     *
     * @return the value of client_car.car_type
     *
     * @mbggenerated
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.car_type
     *
     * @param carType the value for client_car.car_type
     *
     * @mbggenerated
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.owner_phone
     *
     * @return the value of client_car.owner_phone
     *
     * @mbggenerated
     */
    public String getOwnerPhone() {
        return ownerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.owner_phone
     *
     * @param ownerPhone the value for client_car.owner_phone
     *
     * @mbggenerated
     */
    public void setOwnerPhone(String ownerPhone) {
        this.ownerPhone = ownerPhone == null ? null : ownerPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_car.owner_email
     *
     * @return the value of client_car.owner_email
     *
     * @mbggenerated
     */
    public String getOwnerEmail() {
        return ownerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_car.owner_email
     *
     * @param ownerEmail the value for client_car.owner_email
     *
     * @mbggenerated
     */
    public void setOwnerEmail(String ownerEmail) {
        this.ownerEmail = ownerEmail == null ? null : ownerEmail.trim();
    }
}