package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table mechanic_info
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class MechanicInfo extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanic_info.mechanic_id
     *
     * @mbggenerated
     */
    private Integer mechanicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanic_info.mechanic_name
     *
     * @mbggenerated
     */
    private String mechanicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanic_info.mechanic_lv
     *
     * @mbggenerated
     */
    private String mechanicLv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mechanic_info.mechanic_phone
     *
     * @mbggenerated
     */
    private String mechanicPhone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanic_info.mechanic_id
     *
     * @return the value of mechanic_info.mechanic_id
     *
     * @mbggenerated
     */
    public Integer getMechanicId() {
        return mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanic_info.mechanic_id
     *
     * @param mechanicId the value for mechanic_info.mechanic_id
     *
     * @mbggenerated
     */
    public void setMechanicId(Integer mechanicId) {
        this.mechanicId = mechanicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanic_info.mechanic_name
     *
     * @return the value of mechanic_info.mechanic_name
     *
     * @mbggenerated
     */
    public String getMechanicName() {
        return mechanicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanic_info.mechanic_name
     *
     * @param mechanicName the value for mechanic_info.mechanic_name
     *
     * @mbggenerated
     */
    public void setMechanicName(String mechanicName) {
        this.mechanicName = mechanicName == null ? null : mechanicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanic_info.mechanic_lv
     *
     * @return the value of mechanic_info.mechanic_lv
     *
     * @mbggenerated
     */
    public String getMechanicLv() {
        return mechanicLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanic_info.mechanic_lv
     *
     * @param mechanicLv the value for mechanic_info.mechanic_lv
     *
     * @mbggenerated
     */
    public void setMechanicLv(String mechanicLv) {
        this.mechanicLv = mechanicLv == null ? null : mechanicLv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mechanic_info.mechanic_phone
     *
     * @return the value of mechanic_info.mechanic_phone
     *
     * @mbggenerated
     */
    public String getMechanicPhone() {
        return mechanicPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mechanic_info.mechanic_phone
     *
     * @param mechanicPhone the value for mechanic_info.mechanic_phone
     *
     * @mbggenerated
     */
    public void setMechanicPhone(String mechanicPhone) {
        this.mechanicPhone = mechanicPhone == null ? null : mechanicPhone.trim();
    }
}