package com.ricky.carmechanic.domain;

import com.ricky.carmechanic.util.type.BaseEntity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role_privilege
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class RolePrivilege extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.user_role
     *
     * @mbggenerated
     */
    private String userRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.interface_url
     *
     * @mbggenerated
     */
    private String interfaceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_privilege.access_permit
     *
     * @mbggenerated
     */
    private String accessPermit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.user_role
     *
     * @return the value of role_privilege.user_role
     *
     * @mbggenerated
     */
    public String getUserRole() {
        return userRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.user_role
     *
     * @param userRole the value for role_privilege.user_role
     *
     * @mbggenerated
     */
    public void setUserRole(String userRole) {
        this.userRole = userRole == null ? null : userRole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.interface_url
     *
     * @return the value of role_privilege.interface_url
     *
     * @mbggenerated
     */
    public String getInterfaceUrl() {
        return interfaceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.interface_url
     *
     * @param interfaceUrl the value for role_privilege.interface_url
     *
     * @mbggenerated
     */
    public void setInterfaceUrl(String interfaceUrl) {
        this.interfaceUrl = interfaceUrl == null ? null : interfaceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_privilege.access_permit
     *
     * @return the value of role_privilege.access_permit
     *
     * @mbggenerated
     */
    public String getAccessPermit() {
        return accessPermit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_privilege.access_permit
     *
     * @param accessPermit the value for role_privilege.access_permit
     *
     * @mbggenerated
     */
    public void setAccessPermit(String accessPermit) {
        this.accessPermit = accessPermit == null ? null : accessPermit.trim();
    }
}