package com.ricky.carmechanic.mapper;

import com.ricky.carmechanic.domain.CarpartUsage;
import com.ricky.carmechanic.domain.example.CarpartUsageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarpartUsageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int countByExample(CarpartUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int deleteByExample(CarpartUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer usageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int insert(CarpartUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int insertSelective(CarpartUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    List<CarpartUsage> selectByExample(CarpartUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    CarpartUsage selectByPrimaryKey(Integer usageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarpartUsage record, @Param("example") CarpartUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarpartUsage record, @Param("example") CarpartUsageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarpartUsage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_usage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarpartUsage record);
}