package com.ricky.carmechanic.mapper;

import com.ricky.carmechanic.domain.CarpartInfo;
import com.ricky.carmechanic.domain.example.CarpartInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CarpartInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int countByExample(CarpartInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int deleteByExample(CarpartInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer carpartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int insert(CarpartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int insertSelective(CarpartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    List<CarpartInfo> selectByExample(CarpartInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    CarpartInfo selectByPrimaryKey(Integer carpartId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CarpartInfo record, @Param("example") CarpartInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CarpartInfo record, @Param("example") CarpartInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CarpartInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table carpart_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CarpartInfo record);
}