package com.ricky.carmechanic.mapper;

import com.ricky.carmechanic.domain.ClientBill;
import com.ricky.carmechanic.domain.example.ClientBillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int countByExample(ClientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int deleteByExample(ClientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int insert(ClientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int insertSelective(ClientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    List<ClientBill> selectByExample(ClientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    ClientBill selectByPrimaryKey(Integer billId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ClientBill record, @Param("example") ClientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ClientBill record, @Param("example") ClientBillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ClientBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_bill
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ClientBill record);
}