package com.ricky.carmechanic.domain.example;

import java.util.ArrayList;
import java.util.List;

public class MechanicInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public MechanicInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMechanicIdIsNull() {
            addCriterion("mechanic_id is null");
            return (Criteria) this;
        }

        public Criteria andMechanicIdIsNotNull() {
            addCriterion("mechanic_id is not null");
            return (Criteria) this;
        }

        public Criteria andMechanicIdEqualTo(Integer value) {
            addCriterion("mechanic_id =", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdNotEqualTo(Integer value) {
            addCriterion("mechanic_id <>", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdGreaterThan(Integer value) {
            addCriterion("mechanic_id >", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("mechanic_id >=", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdLessThan(Integer value) {
            addCriterion("mechanic_id <", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdLessThanOrEqualTo(Integer value) {
            addCriterion("mechanic_id <=", value, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdIn(List<Integer> values) {
            addCriterion("mechanic_id in", values, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdNotIn(List<Integer> values) {
            addCriterion("mechanic_id not in", values, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdBetween(Integer value1, Integer value2) {
            addCriterion("mechanic_id between", value1, value2, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicIdNotBetween(Integer value1, Integer value2) {
            addCriterion("mechanic_id not between", value1, value2, "mechanicId");
            return (Criteria) this;
        }

        public Criteria andMechanicNameIsNull() {
            addCriterion("mechanic_name is null");
            return (Criteria) this;
        }

        public Criteria andMechanicNameIsNotNull() {
            addCriterion("mechanic_name is not null");
            return (Criteria) this;
        }

        public Criteria andMechanicNameEqualTo(String value) {
            addCriterion("mechanic_name =", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameNotEqualTo(String value) {
            addCriterion("mechanic_name <>", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameGreaterThan(String value) {
            addCriterion("mechanic_name >", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameGreaterThanOrEqualTo(String value) {
            addCriterion("mechanic_name >=", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameLessThan(String value) {
            addCriterion("mechanic_name <", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameLessThanOrEqualTo(String value) {
            addCriterion("mechanic_name <=", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameLike(String value) {
            addCriterion("mechanic_name like", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameNotLike(String value) {
            addCriterion("mechanic_name not like", value, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameIn(List<String> values) {
            addCriterion("mechanic_name in", values, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameNotIn(List<String> values) {
            addCriterion("mechanic_name not in", values, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameBetween(String value1, String value2) {
            addCriterion("mechanic_name between", value1, value2, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicNameNotBetween(String value1, String value2) {
            addCriterion("mechanic_name not between", value1, value2, "mechanicName");
            return (Criteria) this;
        }

        public Criteria andMechanicLvIsNull() {
            addCriterion("mechanic_lv is null");
            return (Criteria) this;
        }

        public Criteria andMechanicLvIsNotNull() {
            addCriterion("mechanic_lv is not null");
            return (Criteria) this;
        }

        public Criteria andMechanicLvEqualTo(String value) {
            addCriterion("mechanic_lv =", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvNotEqualTo(String value) {
            addCriterion("mechanic_lv <>", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvGreaterThan(String value) {
            addCriterion("mechanic_lv >", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvGreaterThanOrEqualTo(String value) {
            addCriterion("mechanic_lv >=", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvLessThan(String value) {
            addCriterion("mechanic_lv <", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvLessThanOrEqualTo(String value) {
            addCriterion("mechanic_lv <=", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvLike(String value) {
            addCriterion("mechanic_lv like", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvNotLike(String value) {
            addCriterion("mechanic_lv not like", value, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvIn(List<String> values) {
            addCriterion("mechanic_lv in", values, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvNotIn(List<String> values) {
            addCriterion("mechanic_lv not in", values, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvBetween(String value1, String value2) {
            addCriterion("mechanic_lv between", value1, value2, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicLvNotBetween(String value1, String value2) {
            addCriterion("mechanic_lv not between", value1, value2, "mechanicLv");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneIsNull() {
            addCriterion("mechanic_phone is null");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneIsNotNull() {
            addCriterion("mechanic_phone is not null");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneEqualTo(String value) {
            addCriterion("mechanic_phone =", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneNotEqualTo(String value) {
            addCriterion("mechanic_phone <>", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneGreaterThan(String value) {
            addCriterion("mechanic_phone >", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("mechanic_phone >=", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneLessThan(String value) {
            addCriterion("mechanic_phone <", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneLessThanOrEqualTo(String value) {
            addCriterion("mechanic_phone <=", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneLike(String value) {
            addCriterion("mechanic_phone like", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneNotLike(String value) {
            addCriterion("mechanic_phone not like", value, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneIn(List<String> values) {
            addCriterion("mechanic_phone in", values, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneNotIn(List<String> values) {
            addCriterion("mechanic_phone not in", values, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneBetween(String value1, String value2) {
            addCriterion("mechanic_phone between", value1, value2, "mechanicPhone");
            return (Criteria) this;
        }

        public Criteria andMechanicPhoneNotBetween(String value1, String value2) {
            addCriterion("mechanic_phone not between", value1, value2, "mechanicPhone");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mechanic_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table mechanic_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}